set(NODE_TOOLS_DIR ${CMAKE_CURRENT_LIST_DIR})
include(${NODE_TOOLS_DIR}/utils.cmake)
include(${NODE_TOOLS_DIR}/projects/targets.cmake)
include(${NODE_TOOLS_DIR}/projects/sources.cmake)
include(${NODE_TOOLS_DIR}/nodejs/index.cmake)
include(${NODE_TOOLS_DIR}/packaging/index.cmake)
